formatter:
  page_width: 100
  trailing_commas: preserve

analyzer:
  exclude:
    - "**/lib/**.g.dart"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    - prefer_relative_imports
    - empty_constructor_bodies
    - unnecessary_primary_constructor_body
    - empty_container_bodies
    - use_declaring_parameters
    - unnecessary_type_name_in_constructor
