include: package:lints/recommended.yaml

analyzer:

# Jaspr has a custom analyzer plugin 'jaspr_lints', which is enabled here.
#
# You can toggle Jaspr specific lint rules in the 'diagnostics' section below.
plugins:
  jaspr_lints:
    version: ^0.7.1
    diagnostics:
      prefer_html_components: true
      sort_children_last: true
      styles_ordering: true

formatter:
  page_width: 120
  trailing_commas: preserve
