analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  plugins:
    jaspr_lints:
      version: ^0.7.1
      diagnostics:
        prefer_html_components: true
        sort_children_last: true
        styles_ordering: true

linter:
  rules:
    - empty_constructor_bodies
    - unnecessary_primary_constructor_body
    - empty_container_bodies
    - use_declaring_parameters
    - unnecessary_type_name_in_constructor

formatter:
  page_width: 100
  trailing_commas: preserve
