name: remote_rift
description: Remote Rift lets you queue for League of Legends games from your phone.
publish_to: none

environment:
  sdk: ^3.13.0

workspace:
  - apps/mobile
  - apps/desktop
  - apps/website
  - packages/api
  - packages/core
  - packages/ui
  - packages/utils
  - packages/tools
  - packages/updater
