name: remote_rift
description: Monorepo workspace for Remote Rift applications and packages.
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - apps/mobile
  - apps/desktop
  - apps/website
  - packages/connector
  - packages/core
  - packages/ui
  - packages/utils
  - packages/tools
  - packages/application_updater
