name: remote_rift_ui
description: Shared UI, theming and Flutter dependent utilities.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  bonsoir: ^7.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
