name: remote_rift_desktop
description: Desktop application exposing connection to the League Client.
version: 0.10.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.1
  flutter_bloc: ^9.1.1
  cancelable_stream: ^1.0.0
  copy_with_extension: ^17.0.0
  http: ^1.6.0
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  tray_manager: ^0.5.2
  equatable: ^2.0.8
  package_info_plus: ^9.0.0
  path: ^1.9.1
  hooks: ^1.0.1

  remote_rift_updater: any
  remote_rift_api: any
  remote_rift_core: any
  remote_rift_ui: any
  remote_rift_utils: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  copy_with_extension_gen: ^17.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
