name: Deploy website to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Add Pub executables to PATH
        run: echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

      - name: Install Jaspr CLI
        run: dart pub global activate jaspr_cli

      - name: Install Tailwind CLI
        run: |
          curl -fsSL -o tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/download/v4.3.0/tailwindcss-linux-x64
          chmod +x tailwindcss
          sudo mv tailwindcss /usr/local/bin/tailwindcss

      - name: Build styles
        run: tailwindcss --input styles.tw.css --output web/styles.css --minify

      - name: Install dependencies
        run: dart pub get

      - name: Build project
        run: jaspr build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/jaspr

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
