name: remote_rift_tools
description: Scripts and utilities used during development.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  path: ^1.9.1

executables:
  update_version:
  generate_asset:
